codecov:
  require_ci_to_pass: yes
  coverage:
    precision: 2
    round: down
    range: "50...100"
    status:
      project:
        default:
          threshold: 50%
          target: 80%
      patch:
        default:
          threshold: 50%
          target: 80%
  comment:
    layout: "reach,diff,flags,tree"
    behavior: default
    require_changes: no
    branches: null
    paths: null
    flags: null
  flags:
    unittests:
      paths:
        - "src/test/java"
      types:
        - unittests