name: API workflow

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest
    name: Test Maven API
    steps:
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: 1b514fa8-56b2-4830-94de-c79acc4e85a2